version: '3.8'
services:
  bybit-p2p:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
    env_file:
      - .env